### ISSUE TITLE
Support installation of zipped wheels and obviate eggs

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#145]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](https://bitbucket.org/jaraco), GitHub: [jaraco](https://github.com/jaraco))**

----------------------------------------

In [Wheel vs Egg](https://packaging.python.org/en/latest/wheel_egg.html), it seems clear that wheel is superior to eggs in every way except one - eggs support direct imports from zipped eggs (through the zip importer). If wheel could support installed zipped wheels, that would enable setuptools to readily replace its usage of eggs with wheels.

According to the PEP, [use of zip eggs is discouraged](https://www.python.org/dev/peps/pep-0427/#is-it-possible-to-import-python-code-directly-from-a-wheel-file), but the primary argument against use of zip wheels assumes that they were copied and not "installed", though setuptools will install eggs, a model which works well in many environments and addresses issues like the file limit on GAE and provides clearer encapsulation.

Is there any reason that zipped wheels couldn't be considered supported as eggs are now even if solely for the purpose of obviating eggs?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/145

**Comment by agronholm** [comment]
@jaraco Is this something that can even be done within the scope of this project? I feel this issue is misplaced here.

**Comment by jaraco** [comment]
I think there are things this project should do. Even if it falls out of scope of the code in the `wheel` Python package, it's the concept of a wheel that would need to be enhanced/extended to provide better support. It's possible that the support may be added in projects like pip or setuptools, but the design should probably start here.

With a zipped egg, assuming it's 'zip-safe', simply adding the egg to `sys.path` is sufficient to make that package available. To make this happen, setuptools exposed metadata in the zip egg in a consistent way and provided APIs for retrieving that metadata. To my knowledge, there was no specification of this design as it was an implementation detail encapsulated in the setuptools/pkg_resources API.

I surmise that wheel does similarly expose metadata in a wheel (as dist-info). Is that metadata location specified and stable? Is there an API for accessing that metadata without expanding the zip file on disk?

I think those are the two things that something like Setuptools would need to be able to use wheels in their compressed format as a single file.

**Comment by pfmoore** [comment]
The wheel spec defines the layout of the wheel file, including [the location of the metadata](https://www.python.org/dev/peps/pep-0427/#the-dist-info-directory). So yes, that data is standards-based and stable.

The wheel PEP also [states](https://www.python.org/dev/peps/pep-0427/#is-it-possible-to-import-python-code-directly-from-a-wheel-file) that while putting wheels on `sys.path` works, and that behaviour is a consequence of the design, it's not a mandated behaviour and relying on it is discouraged.

I'm not sure what else you're expecting? It was pretty explicit in the design process that we didn't want a flag similar to setuptools' `zip-safe` flag - in practice, it had turned out to be fairly unreliable (if only because projects tended not to set it rather than risk users getting errors). So "it works sometimes, but it's your responsibility if you choose to try it" is about as much as you're likely to get.

**Comment by jaraco** [comment]
It sounds like Setuptools should just drop support for zip-based packages.

**Comment by pfmoore** [comment]
Zipped packages (as in zipimport) are perfectly fine, but putting together a general mechanism for creating and using them, as opposed to custom building something project specific, is (as far as I know) still an unsolved problem.

**Comment by coldfix** [comment]
IMHO, wheel should at least preserve the `zip_safe` information. There is no way to otherwise recover this value from the wheel if it was set manually in the `setup.py` by the packager.

That way, installers would be free to choose installation as zip or folder, and creators of embedded installations could easily zip up all packages that do not require to be unpacked. As it currently stands

This can still be a major performance impact on non SSD...
