### ISSUE TITLE
PYPY: running wheel on PyPy and PEP 425 to create packages with binary info

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#187]
Originally reported by: **mattip (Bitbucket: [mattip](https://bitbucket.org/mattip), GitHub: [mattip](https://github.com/mattip))**

----------------------------------------

[PEP 425](https://www.python.org/dev/peps/pep-0425/#python-tag) specifies a Python Tag of the form cp27 for CPython and pp27 for PyPy, but in practice a pure-python wheel packaged by PyPy can run on CPython (and more importantly visa-versa). Wheel currently marks packages produced on PyPy with sys.pypy_version_info() which is not related at all to the sys.version_info() python language implementation.

For packages that contain binary CFFI or CAPI extensions, an additional [ABI tag](https://www.python.org/dev/peps/pep-0425/#abi-tag) is also provided, this IMO should not change from current usage. There is a question what the Python Tag should be for such a package, today it is too specific and contians the entire sys.pypy_version_info(), IMO it should reflect best practices on CPython which would lead to pp27 for python 2.7, pp35 or pp36 for the python 3.5 and 3.6 interpreter.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/187

**Comment by agronholm** [comment]
@mattip Do you still need changes to tagging? If so, what exactly?

**Comment by njsmith** [comment]
There was a thread on pypy-dev last week discussing this, starting here: https://mail.python.org/pipermail/pypy-dev/2017-July/015243.html

My impression is that the pypy team hasn't figured out yet how they want to handle ABI compatibility, and that this bug report might have been a bit premature.

**Comment by mattip** [comment]
@njsmith there are two issues. One is that the Python Tag in ``uWSGI-2.0.14.0.pp257-pypy_41-linux_x86_64.whl`` is wrong, both PyPy for python 2.7 and PyPy for python 3.5 will emit that tag.  So the pp257`` should be ``pp27``or ``pp35``. On that there is agreement, but @agronholm I did not issue a pull request for the one-line change needed since I am not sure how we change that for pip as well, how to make it backward compatible, and how I could test this change.

The PyPy discussion centered on the ABI Tag, which is currently ``pypy_41`` and under what conditions we wish to change that, since it has implications for c-extensions built with the C-API and c-extensions built with CFFI. In any case, the ABI Tag is automatically pulled from a ``sysconfig`` ``configvar``, so changing it will not require changes to wheel or pip.

**Comment by agronholm** [comment]
Negative. I just built a wheel of `psycopg2cffi` with pypy3 5.8.0 and I got `psycopg2cffi-2.7.5-pp358-pypy3_58-linux_x86_64.whl`. What's wrong with that?

**Comment by mattip** [comment]
ok, maybe @njsmith is correct and we still need to work out what we want. Should I close this issue?

**Comment by agronholm** [comment]
Perhaps that would be prudent. You can always open a new issue if you find fault with the way wheel does things.

**Comment by mattip** [comment]
@agronholm it seems to be your issue so you must close it. Sorry for the noise

**Comment by agronholm** [comment]
Ah right. It's an artifact of the github migration.
