### ISSUE TITLE
Limit the scope of "wheel install"

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#197]
The `wheel install` command was added as a proof of concept implementation before wheel installation support was added to pip. Daniel has argued that we should keep this functionality, although I'm not quite sure why. If I were a developing a tool for installing distributions, I would rather look at pip than wheel for an example. If we are to keep `wheel install`, I think it should be a bare-bones installer that only unpacks the wheel contents to their proper locations and installs any console scripts. Handling dependencies or requirements files is just an unnecessary maintenance burden that ultimately serves nobody's interests.

**Comment by agronholm** [comment]
Issue #48 is a good indication of such scope creep.

**Comment by agronholm** [comment]
I'm also on the fence with issue #48.

**Comment by tuukkamustonen** [comment]
As a stupid user of the python packaging system, I hadn't even realized that wheel package comes with `wheel` command, even though I've been building and using wheels for long.

I'm also wonder on the reasons in maintaining `wheel install` command, now that `pip install` can do the same (and more). What is the use case and what are benefits?

**Comment by agronholm** [comment]
It seems that the only purpose of `wheel install` is to provide some kind of "reference implementation". But I'm not sure there's any point in that anymore.

**Comment by vsajip** [comment]
> But I'm not sure there's any point in that anymore.

Perhaps you are right. But if `pip` is going to be the only implementation of everything, why ever bother to standardise? We can go back to the _de facto_ implementation approach of `setuptools` where nothing was standardised. I thought the consensus was that implementation-defined standards were a Bad Thing - has that now changed?

**Comment by agronholm** [comment]
I'm not sure where you're going with this, but `pip` could just as well serve as the reference implementation for here on out. It doesn't mean others won't pop up, but I guess for now it's good enough for most people?

**Comment by agronholm** [comment]
@vsajip The point in standardizing the thing is that people know what to expect from tools, without being subject to the whims of the tool author. If `wheel install` is not going to be actually used in practice, I see little point in keeping it.

**Comment by wvxvw** [comment]
I came here after I realized that the command was removed between versions 0.30.0 and 0.33.4.

And... I'm kind of desperate... there appears to be no tool in entire Python ecosystem capable of installing wheels in a way that would not make you want to cry.

---

Some info for the context, you are welcome to skip it.

So, I'm building a product that needs to be deployed to multiple computers from a programmer's computer. The product is a combination of in-house created packages and some third-party packages hosted by PyPA.  The problem is that in-house created packages are modified way too often for it to make sense to upload them to local PyPI server (the whole versioning doesn't make any sense, not to mention the waste of time).

When I first tried this, I naively used Wheel format: I created a bunch of wheels which I then uploaded to all VMs, and then ran `pip` to install them.  Terrible idea.  `pip` is a disaster.  Too slow, too unreliable, and, scariest of all, it likes to install garbage, i.e. if some requirements have irreconcilable differences, it will go on happily installing whatever nonsense it pleases.

Worse yet, `pip` developers have no interest in fixing any of that.

Another problem with `pip` is that installing it on a Linux system from system's repositories will typically drag along a lot of unnecessary stuff: the entire GCC suite, Autotools and so on.

Being unhappy with `pip` and Wheel in general, I tried installing Eggs with `easy_install`. It worked better in many respects, but, alas, `easy_install` cannot install wheels, and some third-party libraries are only available as Wheels or take forever to build even if they are available as Eggs.  So, again, tons of wasted time...

Needless to say, I also tried to just uploading archived source code and such... but every way I tried, there's a terrible inefficiency typically compounded by the tools producing random and undesirable results.

Then, I discovered that Wheel the tool was sort of able to install Wheels. It didn't do it very well, but compared to other evils, I was able to work around its problems by writing a piece of code that would merge all of in-house built packages into a single Wheel (thus side-stepping the issues related to dependency resolution).

----

And now, here we go again.  The only somewhat useful way of installing Python packages gets removed...

I understand you don't want to believe me that `pip` is not a good package manager and needs an alternative. Especially so my position on Wheel format is... well, I think it's a mistake / too poorly engineered. But, living in the real world, I have to deal with it. So, I have to choose between bad and worse. Removing `install` command from Wheel is the worse of two evils.

**Comment by agronholm** [comment]
> The problem is that in-house created packages are modified way too often for it to make sense to upload them to local PyPI server (the whole versioning doesn't make any sense, not to mention the waste of time).

This is what calendar versioning was invented for (YYYY.MM.DD.postHHMM for example). You can make `setup.py`generate such a version number automatically, and this is what I do in my own projects as well.

> When I first tried this, I naively used Wheel format: I created a bunch of wheels which I then uploaded to all VMs, and then ran pip to install them.

Personally I use Docker for this. Depending on your use case, you might want to consider git submodules too. I'm not sure what the exact problem is that you have though, as your explanation was a bit vague.

> Worse yet, pip developers have no interest in fixing any of that.

Where is this coming from? Just over a week ago I attended the packaging mini-conference at PyCon where the potential addition of a dependency resolver was discussed. All that is missing really is a bunch of capable volunteers with time on their hands.

> Being unhappy with pip and Wheel in general, I tried installing Eggs with easy_install. It worked better in many respects, but, alas, easy_install cannot install wheels, and some third-party libraries are only available as Wheels or take forever to build even if they are available as Eggs. So, again, tons of wasted time...

Eggs were abandoned in favor of wheels because they never had a formal standard in the first place. If you have specific suggestions on how to improve the wheel format or the tools in question, you can start a discussion on the distutils-sig mailing list.

> Needless to say, I also tried to just uploading archived source code and such... but every way I tried, there's a terrible inefficiency typically compounded by the tools producing random and undesirable results.

What specific grievances do you have and with what tools? Have you filed issues on their respective bug trackers?

> So, I have to choose between bad and worse. Removing install command from Wheel is the worse of two evils.

I removed it because it was bad and I had neither the time or energy to make it into a proper installer or even keep it up with the ever changing standards. I'm also sorry if I missed a passage where you volunteered to help.

**Comment by wvxvw** [comment]
> This is what calendar versioning was invented for (YYYY.MM.DD.postHHMM for example). You can make setup.pygenerate such a version number automatically, and this is what I do in my own projects as well.

I don't need a bunch of crap accumulating in repository servers every day (one developer would normally create about 20-30 such versions per day, up to 100 on a good day). No, I don't need this kind of versioning, and I don't want to deal with versioning at all: it's not relevant for the kind of project.

More so, please don't try so second guess my requirements. If I say it's the way it is, then it just is. I know it better than you do, because, I work on it and you don't.

> Personally I use Docker for this.

Good for you. I cannot use Docker for this. My project is more complex.

> Where is this coming from? 

From communication on their bug tracker and mailing list.

> Eggs were abandoned in favor of wheels because they never had a formal standard in the first place. If you have specific suggestions on how to improve the wheel format or the tools in question, you can start a discussion on the distutils-sig mailing list.

I had few discussion on Python mailing list, which convinced me, that if I want something done, then I need to do this on my own.  Had I had enough time to deal with the packaging / distribution, of Python code, I wouldn't be writing here, I'd be working on a solution instead. But I don't have the luxury, that's why I'm here.

Eggs aren't better than Wheels. They are both very bad. It just so happened that `easy_install` works better (at this point in time) than `pip`. That's why I used them. I don't have any sentiments one way or another otherwise.

**Comment by agronholm** [comment]
> I don't need a bunch of crap accumulating in repository servers every day (one developer would normally create about 20-30 such versions per day, up to 100 on a good day). No, I don't need this kind of versioning, and I don't want to deal with versioning at all: it's not relevant for the kind of project.

So how about git submodules? Anyhow, this is a general software deployment issue and not really specific to Python packaging. You would have the same dilemma with Node.js or Ruby too.

> More so, please don't try so second guess my requirements

I had to because you weren't especially forthcoming about them. Frankly it seems that you might be "doing it wrong" but without knowing more about the requirements or the project architecture, I cannot know for sure. Python packaging has many problems at the present but it's a lot better today than it was a few years ago.

> I had few discussions on Python mailing list, which convinced me, that if I want something done, then I need to do this on my own. Had I had enough time to deal with the packaging / distribution, of Python code, I wouldn't be writing here, I'd be working on a solution instead. But I don't have the luxury, that's why I'm here.

What do you expect of me then? This feels like a rant without even a hint of constructive feedback. It seems that you are dissatisfied with the amount of personal time others have spent working on Python packaging but have nothing to contribute yourself.

**Comment by wvxvw** [comment]
> You would have the same dilemma with Node.js or Ruby too.

I don't use Node.js. But I wouldn't have the same problem in Ruby. `gem` doesn't take forever to install packages, is consistent wrt how it installs them, doesn't require me to install a bunch of dependencies to start using it. So, yes, it is a general problem, everyone has to face, but some solved it better than others.

> It seems that you are dissatisfied with the amount of personal time others have spent working on Python packaging

No. I want `wheel install` back. That's all.

**Comment by agronholm** [comment]
> No. I want wheel install back. That's all.

That's not going to happen so my suggestions are:

1. Resurrect the install command from version history and graft that to your own version of wheel
1. File the appropriate issues on the pip bug tracker

If you don't file issues then it's even less likely that the problems you are facing will be resolved by the community.

Frankly I don't understand why running `wheel install` on each wheel would be any different from doing the same with `pip install --no-deps`.

Finally, unless you have constructive comments to add, I kindly ask that you refrain from continuing this discussion.

**Comment by wvxvw** [comment]
> Resurrect the install command from version history and graft that to your own version of wheel

Worthless. My only motivation for using Wheel is that I don't need to support it. If I have to support the package installer, I'd better write my own.

> File the appropriate issues on the pip bug tracker

This has been done long time ago.  Like I said, they don't care about fixing bugs. Not that kind of people.

> Frankly I don't understand why running wheel install on each wheel would be any different from doing the same with pip install --no-deps.

Because installing `pip` is a pain and running it is a pain (too slow, to much unnecessary garbage to install).

**Comment by agronholm** [comment]
> Because installing pip is a pain and running it is a pain (too slow, to much unnecessary garbage to install).

You didn't tell me what OS you were running, but I assume it's a Debian derivative due to the dependencies you described. You can install pip without the extra baggage by doing `apt install --no-install-recommends python3-pip`.

You can also install pip by downloading and running [get-pip.py](https://bootstrap.pypa.io/get-pip.py).

I have no idea what would make pip slower than `wheel install` when skipping dependencies.

**Comment by dholth** [comment]
I'm glad that you enjoyed the wheel install command.

There are alternative installers including distlib https://pythonhosted.org/distlib/tutorial.html#installing-from-wheels

**Comment by vsajip** [comment]
> There are alternative installers including distlib

Yes, but that's library functionality rather than a command that installs wheels. Not a big script to write to use it, of course.

**Comment by agronholm** [comment]
What I would've been interested in hearing is what makes pip slower than `wheel install` when dependencies are left out. Doesn't it do pretty much the same things?
