### ISSUE TITLE
Wheel created by bdist_wheel has nothing but dist-info AND egg-info

### ISSUE THREAD

**Issue by wvxvw** [pypa/wheel#412]
Well, this is hilarious.

The amount of validation is staggering! I almost rolled under my desk after I looked at the generated wheel.

Good job guys.

I wish you spent more time working on your code of conduct. It certainly helps to improve the quality of your code!

**Comment by agronholm** [comment]
I looked into your comment history and this is not the only project where you have posted toxic comments such as this. Thus I've reported you to Github. Not sure if anything will happen from that, but I felt it needed to be done.

The text in this issue indicates that you are simply venting your frustration at us and are not even trying to explain what the circumstances that led to the problem are. If you had a little more patience to work with us instead of losing your temper every time someone asks for more information or doesn't understand what you're saying, we could possibly help you solve the problems you are encountering. Remember that we are volunteers, not paid employees of PSF or another organizational entity. Thus it seems quite unfair, especially for a non-contributor such as yourself, to mock the software that we improve on our free time. 

If you could explain the issue in depth, we would at least have a chance at looking into it. Have you also considered that you yourself might be doing something wrong? Surely there are known bugs and gaps in functionality, but hundreds of thousands of developers use these tools every day without major issues.

**Comment by wvxvw** [comment]
No, it's not my frustration. I explained before.

In order to convince people who pay my salary not to use your tools, I need tangible proof of how bad they are, and how incompetent their maintainers are.

Report me wherever you want. I couldn't care less. I just want people to stop using PyPAs garbage. And I'll  do as much as I can to get the message spread further.

**Comment by agronholm** [comment]
Why do you keep creating these issues then? What do you hope to accomplish?

**Comment by wvxvw** [comment]
> What do you hope to accomplish?

Yes, once again, a PyPA member fails to read an extremely short and easy message... idk. not sure if repeating it will be any use:

> I just want people to stop using PyPAs garbage. And I'll do as much as I can to get the message spread further.

**Comment by agronholm** [comment]
I read your message, but it's not clear to me how creating these issues would further that goal.

**Comment by wvxvw** [comment]
Well... idk. Think. Maybe you'll think about something. I cannot help you there.
