### ISSUE TITLE
FR: Add option to add more data to the `Generator` in the `WHEEL` file

### ISSUE THREAD

**Issue by ofek** [pypa/wheel#479]
ref: https://github.com/pypi/warehouse/issues/12436#issuecomment-1295062407

So users can tell which version of `setuptools` was responsible for builds

**Comment by fungi** [comment]
In particular, PEP 517 build backends which leverage the wheel library's writer (in order to not reinvent the....) could benefit from being able to plumb generator metadata through somehow. This includes SetupTools as a build backend, as well as other backends which extend SetupTools (e.g. calling into the setuptools.build_meta.build_wheel() method), but theoretically could also apply to non-SetupTools-based backends as well.

**Comment by agronholm** [comment]
I think I can close this now that setuptools has its own `bdist_wheel` that uses the proper setuptools version in `WHEEL`.
