### ISSUE TITLE
wheel 0.40 is missing license metadata

### ISSUE THREAD

**Issue by vulli321** [pypa/wheel#518]
wheel 0.38:
```
importlib.metadata.metadata("wheel").get("License")
'MIT'
```

wheel 0.40:
```
importlib.metadata.metadata("wheel").get("License")
None
```

this breaks some of my ci scripts, is this an intended consequence of moving to pyproject.toml?

**Comment by henryiii** [comment]
The License field is really only supposed to be filled in if it is not possible to specify the license via Trove classifiers, or if a version or modification is required. If it's not, then License is supposed to be the full text of the license. See https://packaging.python.org/en/latest/specifications/core-metadata/#license.

That said, I'm a little surprised it doesn't contain the full text of the license, as we are setting `license = {file = "LICENSE.txt"}`, such as in https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license.

We could probably change it to `license = {text = "MIT"}` to exactly replicate the old metadata. I'd have to check.

**Comment by henryiii** [comment]
Flit does not fill the `License` field at all regardless of what's in `license=`, since the PEP 621 `license` field is for the full text of the license, while the `License` metadata field is an optional short "comment" of sorts on the license. See https://github.com/pypa/flit/blob/532bdaabafe0660b6c7494d8043ec4fa15b286a8/flit_core/flit_core/config.py#L509-L524, @takluyver could possibly comment if I didn't interpret correctly.

Again, `importlib.metadata.metadata("wheel").get("License")` is not the correct way to get the license of a project since metadata 1.1, covered in [PEP 314](https://peps.python.org/pep-0314/#license) (PEP π!), from 2003. (It _was_ correct before that, in metadata 1.0 & [PEP 241](https://peps.python.org/pep-0241/) from 2001, FYI).

**Comment by vulli321** [comment]
i'm sure i looked at the packaging docs, but somehow i still missed that... thanks for the explanation :)

**Comment by takluyver** [comment]
My original understanding was that the `license = {text = "..."}` option in the TOML was meant for full license text, but the example [in the spec](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license) is `license = {text = "MIT License"}`, and the definition is vague ("a string value which is the license of the project").

I had also simply been postponing doing anything about this since it seemed like PEP 639 would give us a better way to expose license metadata. But that seems to have got stuck somewhere - it still has draft status - so maybe we need to do something in the meantime. Although without that, there's no standardisation to tell us whether you write e.g. 'MIT' or 'MIT License' or 'M.I.T.' or 'Expat' and so on.
