### ISSUE TITLE
How to ERRADICATE the wheel in PIP

### ISSUE THREAD

**Issue by Elsarques** [pypa/wheel#625]
Almost everytime I try to install something on termux with pip, it just throws an error when getting the requirements to build the wheel, ALMOST EVERYTIME, so I need an argument to disable it or ERRADICATE IT FROM MY PIP INSTALATION, thanks

**Comment by henryiii** [comment]
More of error message? The error message “failed to get requirements to build **the** wheel” has nothing to do with the wheel package. It means you can’t get wherever the package needs to build. A build package in Python is a wheel.

**Comment by henryiii** [comment]
That’s Python 2 syntax. You are trying to build a package that was never updated to Python 3. “pip install” makes a wheel then installs it. If the package fails, you’ll see a message mentioning issues making the wheel, but that’s just because that’s how the install process works.

—no-build-isolation will change the error message, but it will likely still be broken. The package you are trying to install was abandoned 10 years ago.

**Comment by Elsarques** [comment]
> That’s Python 2 syntax. You are trying to build a package that was never updated to Python 3. “pip install” makes a wheel then installs it. If the package fails, you’ll see a message mentioning issues making the wheel, but that’s just because that’s how the install process works.
> 
> —no-build-isolation will change the error message, but it will likely still be broken. The package you are trying to install was abandoned 10 years ago.

I see, thanks, i'm trying to make PyOpenGL run on termux, but everytime I import a library other than OpenGL, it doesn't work, but anyway, thanks for explaining me that, I would probably try again to install for more 6 hours after giving up, now I will try to make the imports work instead of installing another package

**Comment by AraHaan** [comment]
Unlike them, I wish I could figure out a way to subclass pip's wheel implementation and force pip to use it instead for when a package needs to:

- build C extensions

To also build a ``<c extension name><pyd tag (without the .pyd)>_static.lib`` on top of the normal pyd gen so advanced users wanting to embed python into a single file can static link every single C extension (along with the python core and the default C extensions within the cpython repository itself. This is because on Windows loading the python core manually after extracting it from the exe (to bootstrap from single file) using ``LoadLibraryA`` or using the MemoryModule code (to load the dll from memory) both won't work because the usage of ``__declspec(thread)`` seems to not be properly initialized (via the hidden and non-exported ``ntdll.dll!LdrpHandleTLSData``) as it seems the required function to initliaze the TLS (Thread Local Storage) is not called before the DllMain is run.

Perhaps there is a way to pull request to pip to add such a thing directly instead as an optional argument to ``pip install -r requirements.txt`` that would create said static builds on top of the normal pyd generation?

**Comment by agronholm** [comment]
Maybe that should be discussed somewhere more appropriate? This is just a command line tool to manipulate wheel files and converts other formats to wheel.

**Comment by henryiii** [comment]
You'd need to work with each of the backends (setuptools, scikit-build-core, meson-python, maturin at least) unless you can do it by processing the .so files.
