### ISSUE TITLE
Preserve symbolic links

### ISSUE THREAD

**Issue by mwtoews** [pypa/wheel#628]
With wheel 0.43.0 it seems that symbolic links are converted to regular files. This support request is to preserve symbolic links as they exist in the host file system.

I'm unsure if this is from `wheel unpack` and/or `wheel pack`, as I use both of these utilities to re-arrange a few files within a cibuildwheel process, and have noticed this difference. Note that setuptools' commands (based on distutils) support symbolic links with their inner-workings, but appear to be "off" by default (e.g. [here](https://github.com/pypa/distutils/blob/4e6d97db1b4364cb184960f477c3e78435332646/distutils/file_util.py#L83-L88) and [here](https://github.com/pypa/distutils/blob/4e6d97db1b4364cb184960f477c3e78435332646/distutils/dir_util.py#L126-L131)).

**Comment by mwtoews** [comment]
I should note that I don't have any need for this feature. My workaround was to remove symlinks from being created. In my particular scenario I used [`CMAKE_PLATFORM_NO_VERSIONED_SONAME=ON`](https://cmake.org/cmake/help/latest/variable/CMAKE_PLATFORM_NO_VERSIONED_SONAME.html).

The issue still stands, but with a low priority since it's probably not a show-stopper for anyone.

**Comment by agronholm** [comment]
There is a larger discussion around the topic of symbolic links in wheels, [here](https://discuss.python.org/t/pep-778-supporting-symlinks-in-wheels/53824/56). As this project is going to be reduced to a CLI tool only going forward (when https://github.com/pypa/packaging/pull/805 lands), this issue is no longer relevant to this project anyway.
